config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many  :doses
  has_many  :ingredients, through: :doses, dependent: :destroy
  has_many  :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: (0..5).to_a }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all

    if params[:search]
      @query = query_params[:query]
      @cocktails = Cocktail.where("lower(name) LIKE lower(?)", "%#{@query}%")
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @cocktail_doses = Dose.where(cocktail: @cocktail)
    @new_dose = Dose.new
    @ingredients = Ingredient.all

    @cocktail_reviews = Review.where(cocktail: @cocktail)
    @new_review = Review.new
  end

  def new
    @new_cocktail = Cocktail.new
  end

  def create
    @new_cocktail = Cocktail.new(cocktail_params)
    if @new_cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def edit
    set_cocktail
  end

  def update
    set_cocktail
    if @cocktail.update(cocktail_params)
      redirect_to cocktails_path
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy

    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end

  def query_params
    params.require(:search).permit(:query)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @new_dose = Dose.new(dose_params)
    @new_dose.cocktail = @cocktail

    @cocktail_doses = Dose.where(cocktail: @cocktail)
    @ingredients = Ingredient.all

    @cocktail_reviews = Review.where(cocktail: @cocktail)
    @new_review = Review.new

    if @new_dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail.id)

    @dose.destroy

    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @new_review = Review.new(review_params)
    @new_review.cocktail = @cocktail

    @new_dose = Dose.new
    @cocktail_doses = Dose.where(cocktail: @cocktail)
    @cocktail_reviews = Review.where(cocktail: @cocktail)
    @ingredients = Ingredient.all

    if @new_review.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @cocktail = Cocktail.find(@review.cocktail.id)

    @review.destroy

    redirect_to cocktail_path(@cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/edit.html.erb
<div class="container my-3 min-vh-100">
  <div class="row">
    <div class="col-12 col-lg-6 m-auto bg-white p-4 rounded">
      <h1>Edit this cocktail</h1>
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Back to List", cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container my-3 min-vh-100">
  <h1>List of Cocktails</h1>

  <% if @query %>
  <p>Result search for <strong><%= @query %></strong>. (<%= @cocktails.count %> cocktails)</p>
  <% else %>
  <p>List all cocktails. (<%= @cocktails.count %> cocktails)</p>
  <% end %>

  <div class="cards">
    <% @cocktails.each do |cocktail| %>
    <div class="card">
      <% if cocktail.photo.attached? %>
      <%= cl_image_tag cocktail.photo.key, crop: :fill %>
      <% else %>
      <img src="https://source.unsplash.com/400x300/?cocktail" class="card-img-top" alt="<%= cocktail.name %>">
      <% end %>
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h5 class="card-title"><strong><%= cocktail.name %></strong></h5>
          <div class="stars">
            <% average_rating = Review.where(cocktail: cocktail).average(:rating) || 0 %>
            <% average_rating.floor.times do %>
            <i class="fas fa-star"></i>
            <% end %>
            <% (5-average_rating.floor).times do %>
            <i class="far fa-star"></i>
            <% end %>
          </div>
        </div>
        <p class="card-text"><%= cocktail.description %></p>
      </div>
      <div class="card-bottom d-flex justify-content-between align-items-center">
        <%= link_to "Explore", cocktail_path(cocktail), class: "btn btn-primary" %>
        <div class="d-flex">
          <%= link_to edit_cocktail_path(cocktail), class: "text-success mr-1" do%>
          <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to cocktail_path(cocktail), method: "delete", class: "text-warning" do%>
          <i class="far fa-trash-alt"></i>
          <% end %>
        </div>

      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container my-3 min-vh-100">
  <div class="row">
    <div class="col-12 col-lg-6 m-auto bg-white p-4 rounded">
      <h1>Add new cocktail</h1>
      <%= simple_form_for @new_cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Back to List", cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<%= render "shared/banner" %>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="flat-card bg-light p-4 rounded">
        <h1><strong><%= @cocktail.name %></strong></h1>
        <div class="stars my-2">
          <% average_rating = Review.where(cocktail: @cocktail).average(:rating) || 0 %>
          <% review_count = Review.where(cocktail: @cocktail).count || 0 %>
          <% average_rating.floor.times do %>
          <i class="fas fa-star"></i>
          <% end %>
          <% (5-average_rating.floor).times do %>
          <i class="far fa-star"></i>
          <% end %>
          <br>
          <%= average_rating.round(2) %> out of 5
          (<%= review_count %> reviews)
        </div>
        <h3><%= @cocktail.description %></h3>
      </div>
      <div class="flat-card flat-card-description bg-light p-4 my-3 rounded">
        <h2>Ingredients :</h2>
        <ul>
          <% @cocktail_doses.each do |dose| %>
          <li class="d-flex justify-content-between">
            <span><i class="fas fa-circle icon-small"></i> <%= dose.description %> <%= dose.ingredient.name %></span>
            <span>
              <%= link_to dose_path(dose), method: "delete", class: "delete-button" do%>
              <i class="far fa-trash-alt"></i>
              <% end %>
            </span>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="flat-card flat-card-description bg-light p-4 my-3 rounded">
        <h2>Reviews :</h2>
        <% @cocktail_reviews.each do |review| %>
        <div class="review-card p-1 my-2">
          <div class="review-card-top d-flex justify-content-between pb-2">
            <div class="stars">
              <% review.rating.times do %>
              <i class="fas fa-star"></i>
              <% end %>
              <% (5-review.rating).times do %>
              <i class="far fa-star"></i>
              <% end %>
            </div>
            <%= link_to review_path(review), method: "delete", class: "delete-button" do%>
            <i class="far fa-trash-alt"></i>
            <% end %>
          </div>
          <div class="review-card-body">
            "<%= review.content %>"
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-lg-4">
      <div class="flat-card bg-light p-4 rounded">
        <h5>Add new ingredient to <%= @cocktail.name %> </h5>
        <%= simple_form_for [@cocktail, @new_dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient, as: :select %>
        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="flat-card bg-light p-4 my-3 rounded">
        <h5>Add new review for <%= @cocktail.name %> </h5>
        <%= simple_form_for [@cocktail, @new_review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <%= link_to "Back to List", cocktails_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style='background-image: url(
<% if @cocktail.photo.attached? %>
<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
<% else %>
<%= "https://source.unsplash.com/400x300/?cocktail" %>
<% end %>
);'>
  <div class="container">

  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer mt-3">
  <div class="footer-links">
    <a href="https://github.com/nielsantosa/rails-mister-cocktail"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/nielsantosa/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/lewagonsingapore/?brand_redir=116941945171079"><i class="fab fa-facebook"></i></a>
    <a href="https://www.lewagon.com/singapore"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/le-wagon/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> Nathaniel Santosa &copy2021
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "Cocktailzilla", cocktails_path ,class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item mx-1">
        <%= render "shared/search_form" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktail", new_cocktail_path, class: "btn btn-primary btn-add-cocktail mx-1" %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_search_form.html.erb
<form novalidate="novalidate" class="simple_form search" action="/cocktails" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Search cocktail"/>
    <button type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i>
    </button>
  </div>
</form>